version: "3.6"

networks:
  splunknet:
    driver: bridge
    attachable: true

volumes:
  sh1:
  sh2:
  sh3:
  dep1:
  cm1:
  idx1:
  idx2:
  idx3:
  idx4:

services:
  sh1:
    networks:
      splunknet:
        aliases:
          - sh1
    image: ${SPLUNK_IMAGE}
    # command: tail -F /dev/null
    command: 
      - /bin/sh
      - -c
      - |
        /opt/splunk/bin/splunk start && tail -f /dev/null
    hostname: sh1
    container_name: sh1
    ports:
      - 8001:8000
      - 8089  # Management 
      - 9777  # Search Head Cluster 
      - 8191  # KV Store Replication
    volumes:
      - sh1:/opt
    depends_on:
      - traefik
    labels:
      - "traefik.http.routers.sh1.rule=Host(`sh1.localhost`)"
    

  sh2:
    networks:
      splunknet:
        aliases:
          - sh2
    image: ${SPLUNK_IMAGE}
    # command: tail -F /dev/null
    command: 
      - /bin/sh
      - -c
      - |
        /opt/splunk/bin/splunk start && tail -f /dev/null
    hostname: sh2
    container_name: sh2
    ports:
      - 8002:8000
      - 8089  # Management 
      - 9777  # Search Head Cluster 
      - 8191  # KV Store Replication
    volumes:
      - sh2:/opt
    depends_on:
      - traefik
    labels:
      - "traefik.http.routers.sh2.rule=Host(`sh2.localhost`)"

  sh3:
    networks:
      splunknet:
        aliases:
          - sh3
    image: ${SPLUNK_IMAGE}
    # command: tail -F /dev/null
    command: 
      - /bin/sh
      - -c
      - |
        /opt/splunk/bin/splunk start && tail -f /dev/null
    hostname: sh3
    container_name: sh3
    ports:
      - 8003:8000
      - 8089  # Management 
      - 9777  # Search Head Cluster 
      - 8191  # KV Store Replication
    volumes:
      - sh3:/opt
    depends_on:
      - traefik
    labels:
      - "traefik.http.routers.sh3.rule=Host(`sh3.localhost`)"

  dep1:
    networks:
      splunknet:
        aliases:
          - dep1
    image: ${SPLUNK_IMAGE}
    # command: tail -F /dev/null
    command: 
      - /bin/sh
      - -c
      - |
        /opt/splunk/bin/splunk start && tail -f /dev/null
    hostname: dep1
    container_name: dep1
    ports:
      - 8004:8000
      - 8089  # Management 
    volumes:
      - dep1:/opt
    depends_on:
      - traefik
    labels:
      - "traefik.http.routers.dep1.rule=Host(`dep1.localhost`)"

  cm1:
    networks:
      splunknet:
        aliases:
          - cm1
    image: ${SPLUNK_IMAGE}
    # command: tail -F /dev/null
    command: 
      - /bin/sh
      - -c
      - |
        /opt/splunk/bin/splunk start && tail -f /dev/null
    hostname: cm1
    container_name: cm1
    ports:
      - 8005:8000
      - 8089  # Management 
    volumes:
      - cm1:/opt
    depends_on:
      - traefik
    labels:
      - "traefik.http.routers.cm1.rule=Host(`cm1.localhost`)"


  idx1:
    networks:
      splunknet:
        aliases:
          - idx1
    image: ${SPLUNK_IMAGE}
    # command: tail -F /dev/null
    command: 
      - /bin/sh
      - -c
      - |
        /opt/splunk/bin/splunk start && tail -f /dev/null
    hostname: idx1
    container_name: idx1
    ports:
      - 8006:8000
      - 8089  # Management 
      - 9997  # Splunk Data
      - 9887  # Index Replication
    volumes:
      - idx1:/opt
    depends_on:
      - traefik
    labels:
      - "traefik.http.routers.idx1.rule=Host(`idx1.localhost`)"

  idx2:
    networks:
      splunknet:
        aliases:
          - idx2
    image: ${SPLUNK_IMAGE}
    # command: tail -F /dev/null
    command: 
      - /bin/sh
      - -c
      - |
        /opt/splunk/bin/splunk start && tail -f /dev/null
    hostname: idx2
    container_name: idx2
    ports:
      - 8007:8000
      - 8089  # Management 
      - 9997  # Splunk Data
      - 9887  # Index Replication
    volumes:
      - idx2:/opt
    depends_on:
      - traefik
    labels:
      - "traefik.http.routers.idx2.rule=Host(`idx2.localhost`)"

  idx3:
    networks:
      splunknet:
        aliases:
          - idx3
    image: ${SPLUNK_IMAGE}
    # command: tail -F /dev/null
    command: 
      - /bin/sh
      - -c
      - |
        /opt/splunk/bin/splunk start && tail -f /dev/null
    hostname: idx3
    container_name: idx3
    ports:
      - 8008:8000
      - 8089  # Management 
      - 9997  # Splunk Data
      - 9887  # Index Replication
    volumes:
      - idx3:/opt
    depends_on:
      - traefik
    labels:
      - "traefik.http.routers.idx3.rule=Host(`idx3.localhost`)"



  traefik:
    networks:
      splunknet:
        aliases:
          - traefik    
    image: traefik:v3.0
    command: --api.insecure=true --providers.docker
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
